CREATE TABLE TBLMOVIES(
	id int IDENTITY(1,1) PRIMARY KEY,
	year int,
	title varchar,
	winner bool
);

CREATE TABLE TBLPRODUCERS(
	id int IDENTITY(1,1) PRIMARY KEY,
	name varchar
);

CREATE TABLE TBLMOVIEPRODUCERS(
	PRODUCER_ID int,
	MOVIE_ID int
);

CREATE TABLE TBLSTUDIOS(
	id int IDENTITY(1,1) PRIMARY KEY,
	name varchar
);

CREATE TABLE TBLMOVIESTUDIOS(
	STUDIO_ID int,
	MOVIE_ID int
);